blank_issues_enabled: false
contact_links:
  - name: Technical Issues
    url: https://snapmaker.formcrafts.com/u1-troubleshooting-request
    about: For trickier problems, you can submit a support request here
